[package]
name = "hue"
version = "0.1.0"
authors = ["Dominik Russo"]
license = "GPL-3.0-or-later"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hueclient = "0.4.1"
structopt = "0.3.25"
