[package]
name = "hue"
version = "0.1.0"
authors = ["Dominik Russo"]
license = "GPL-3.0-only"
edition = "2021"
rust-version = "1.56.0"

[profile.release]
lto = "fat"
strip = "symbols"

[dependencies]
huelib = "0.13.2"
pastel = "0.9.0"
structopt = "0.3.25"
xdg = "2.4.0"
